language: csharp
sudo: required
mono: none
dotnet: 2.1.300
services:
    - docker
branches:
  only:
    - master
    - develop
before_script:
  - chmod a+x ./build-server.sh
script:
  - ./build-server.sh
notifications:
  email:
    on_success: never
    on_failure: always